name: MobArmyWars
version: "1.7"
author: Runi
main: runi.myddns.mobarmywars.MobArmyMain
api-version: '26.2'
description: MobArmyWars - inspired by BastiGHG

commands:
  language:
    description: Opens the language selection
    usage: /language

  arenasummary:
    description: Shows the arena summary
    usage: /arenasummary

  mobarmy:
    description: Main command for MobArmyWars
    usage: /mobarmy resume
    aliases: [ma]
    permission: mobarmy.admin
    permission-message: "§c❌ You do not have permission!"

  mobstatus:
    description: Shows saved mobs
    usage: /mobstatus [rot|blau]

  optionen:
    description: Opens the MobArmyWars options
    usage: /optionen
    permission: mobarmy.admin
    permission-message: "§c❌ You do not have permission!"

  resume:
    description: Resume function for MobArmyWars
    usage: /resume mobarmy
    aliases: [continue]
    permission: mobarmy.admin
    permission-message: "§c❌ You do not have permission!"

  setphase:
    description: Sets the event phase
    usage: /setphase <lobby|teamwelt|waveauswahl|arena>
    permission: mobarmy.admin
    permission-message: "§c❌ You do not have permission!"

  team:
    description: Team commands
    usage: /team <join|leave> [rot|blau]

  reset:
    description: Reset commands for MobArmyWars
    usage: /reset <arena|lobby|teamworld|playerdata>
    permission: mobarmy.admin
    permission-message: "§c❌ You do not have permission!"

permissions:
  mobarmy.admin:
    default: op

  mobarmy.mobstatus.admin:
    description: Allows viewing mob status for all teams
    default: op